// Cocktailrecepten voor de blog (/recepten/<slug>/).
// Na een wijziging: node tools/build.js

module.exports = [
  {
    slug: "espresso-martini",
    name: "Espresso Martini",
    color: ["#8a5a3c", "#2e1d13"],
    short: "Koffie en cocktail in één, met een dikke schuimlaag.",
    lead: "Koffie en cocktail in één glas, met die mooie schuimlaag bovenop. Zo maak je een Espresso Martini die niet onderdoet voor die in de bar.",
    glass: "Coupe",
    technique: "Shaken",
    level: "Gemiddeld",
    time: 5,
    ingredients: [["50 ml", "wodka"], ["25 ml", "koffielikeur"], ["25 ml", "vers gezette espresso"], ["10 ml", "suikersiroop (optioneel)"], ["3", "koffiebonen"]],
    tools: "Shaker, strainer, fijne zeef, ijsblokjes en een gekoeld glas.",
    intro: [
      "De Espresso Martini werd in de jaren tachtig in Londen bedacht en is inmiddels een van de populairste cocktails ter wereld.",
      "Het geheim zit niet in dure ingrediënten, maar in verse espresso en hard shaken. Daar komt het schuimlaagje vandaan.",
    ],
    steps: [
      "Zet een espresso en laat hem even afkoelen. Een lungo of oploskoffie geeft minder smaak en minder schuim.",
      "Zet je glas in de vriezer of vul het met ijs en water, zodat het koud is als je gaat inschenken.",
      "Doe wodka, koffielikeur, espresso en eventueel suikersiroop in de shaker.",
      "Vul de shaker helemaal met ijs en shake 15 seconden zo hard als je kunt.",
      "Gooi het ijswater uit je glas en schenk de cocktail door de strainer en een fijne zeef in het glas.",
      "Leg drie koffiebonen op het schuim.",
    ],
    tip: "Shake langer en harder dan je denkt. Hoe meer lucht je erin slaat, hoe dikker en mooier de schuimlaag.",
    mistakes: [
      "Te weinig ijs in de shaker: de cocktail wordt dan waterig in plaats van koud.",
      "Oude of slappe koffie: de espresso bepaalt de smaak.",
      "Niet zeven: kleine ijsschilfers maken het schuim onrustig.",
    ],
    variation: ["Salted Caramel Espresso Martini", "Vervang de suikersiroop door 10 ml karamelsiroop en voeg een klein snufje zout toe. Zoet, zout en bitter tegelijk."],
  },
  {
    slug: "pornstar-martini",
    name: "Pornstar Martini",
    color: ["#f3b24c", "#e0673a"],
    short: "Fruitig en fris, met een shotje bubbels ernaast.",
    lead: "Fruitig, fris en met een shotje bubbels ernaast. De Pornstar Martini is al jaren een favoriet op feestjes. Zo maak je hem zelf.",
    glass: "Coupe",
    technique: "Shaken",
    level: "Gemiddeld",
    time: 5,
    ingredients: [["40 ml", "vanillewodka"], ["15 ml", "passievruchtlikeur"], ["1", "passievrucht (of 30 ml passievruchtpuree)"], ["15 ml", "vers limoensap"], ["10 ml", "vanillesiroop"], ["60 ml", "prosecco, apart geserveerd"]],
    tools: "Shaker, strainer, fijne zeef, een coupeglas en een shotglas.",
    intro: [
      "Ook deze cocktail komt uit Londen en werd rond de eeuwwisseling bedacht. Binnen een paar jaar stond hij op bijna elke cocktailkaart.",
      "Typisch is het shotje prosecco dat je ernaast serveert. Je drinkt het apart of schenkt het erbij, net wat je lekker vindt.",
    ],
    steps: [
      "Halveer de passievrucht. Schep de ene helft uit in de shaker, de andere helft bewaar je voor de garnering.",
      "Voeg vanillewodka, passievruchtlikeur, limoensap en vanillesiroop toe.",
      "Vul de shaker met ijs en shake ongeveer 15 seconden stevig.",
      "Schenk door een strainer en fijne zeef in een gekoeld coupeglas, zodat de pitjes achterblijven.",
      "Leg de halve passievrucht op de cocktail.",
      "Serveer met een shotglas koude prosecco ernaast.",
    ],
    tip: "Geen vanillewodka in huis? Neem gewone wodka en verhoog de vanillesiroop naar 15 ml.",
    mistakes: [
      "De pitjes niet zeven: dan drink je een mondvol pitten.",
      "Lauwe prosecco: zet de fles vooraf goed koud.",
      "Te veel siroop: passievrucht is van zichzelf al zoet.",
    ],
    variation: ["Alcoholvrije Pornstar", "Laat de wodka en likeur weg, gebruik 50 ml passievruchtsap en serveer met alcoholvrije bubbels."],
  },
  {
    slug: "mojito",
    name: "Mojito",
    color: ["#b9dd8c", "#4f8f4a"],
    short: "Munt, limoen en rum: het ultieme zomerdrankje.",
    lead: "Munt, limoen en rum: de Mojito is het ultieme zomerdrankje. Met deze stappen maak je er een die fris blijft tot de laatste slok.",
    glass: "Longdrinkglas",
    technique: "Bouwen in het glas",
    level: "Makkelijk",
    time: 5,
    ingredients: [["50 ml", "witte rum"], ["25 ml", "vers limoensap"], ["20 ml", "suikersiroop"], ["8–10", "muntblaadjes"], ["", "crushed ijs"], ["", "bruiswater om aan te vullen"]],
    tools: "Longdrinkglas, stamper of lepel, barlepel en crushed ijs.",
    intro: [
      "De Mojito komt uit Cuba, waar rum, limoen en munt al generaties samengaan.",
      "Een goede Mojito staat of valt met verse munt en het juiste ijs. Met crushed ijs blijft hij koud zonder snel waterig te worden.",
    ],
    steps: [
      "Leg de muntblaadjes in het glas en druk ze zachtjes aan met een stamper. Niet fijnstampen, anders wordt de munt bitter.",
      "Voeg limoensap en suikersiroop toe.",
      "Vul het glas voor twee derde met crushed ijs en schenk de rum erbij.",
      "Roer met een barlepel van onder naar boven, zodat de munt door het glas verdeeld wordt.",
      "Vul aan met crushed ijs en een scheut bruiswater.",
      "Garneer met een takje munt.",
    ],
    tip: "Klap het takje munt voor de garnering even tussen je handen. Dan komt de geur vrij en ruik je de munt al voordat je de eerste slok neemt.",
    mistakes: [
      "De munt kapotstampen: je wilt de olie eruit drukken, niet de blaadjes vermalen.",
      "Limoensap uit een fles: vers geperst smaakt veel frisser.",
      "Te veel bruiswater: dat verdunt de smaak. Een scheutje is genoeg.",
    ],
    variation: ["Virgin Mojito", "Laat de rum weg en vul aan met extra bruiswater of ginger ale. Net zo fris, zonder alcohol."],
  },
  {
    slug: "whiskey-sour",
    name: "Whiskey Sour",
    color: ["#f2c36b", "#b5742a"],
    short: "Zoet, zuur en met een zijdezachte schuimkraag.",
    lead: "Zoet, zuur en een zijdezachte schuimkraag. De Whiskey Sour is een klassieker die iedereen zou moeten kunnen maken.",
    glass: "Tumbler",
    technique: "Dry shake en shaken",
    level: "Gemiddeld",
    time: 5,
    ingredients: [["50 ml", "bourbon"], ["25 ml", "vers citroensap"], ["20 ml", "suikersiroop"], ["1", "eiwit (of 25 ml aquafaba)"], ["2–3 druppels", "Angostura bitters"]],
    tools: "Shaker, strainer, tumbler en ijsblokjes.",
    intro: [
      "De Whiskey Sour bestaat al sinds de negentiende eeuw en is de basis van een hele familie 'sours'.",
      "Het eiwit geeft geen smaak, maar zorgt voor de fluweelzachte textuur en de schuimlaag. Liever geen ei? Aquafaba, het vocht uit een blik kikkererwten, werkt net zo goed.",
    ],
    steps: [
      "Doe bourbon, citroensap, suikersiroop en eiwit in de shaker.",
      "Shake eerst 10 seconden zonder ijs. Deze 'dry shake' klopt het eiwit op.",
      "Voeg ijs toe en shake nog eens 15 seconden stevig.",
      "Schenk door een strainer in een tumbler met verse ijsblokjes.",
      "Laat een paar druppels Angostura op het schuim vallen.",
    ],
    tip: "Trek met een cocktailprikker door de druppels bitters. Zo maak je in een paar seconden een mooi patroon op het schuim.",
    mistakes: [
      "Direct met ijs shaken: zonder dry shake krijg je nauwelijks schuim.",
      "Citroensap uit een fles: vers sap geeft de frisheid die deze cocktail nodig heeft.",
      "Het ijs uit de shaker hergebruiken: dat is al half gesmolten.",
    ],
    variation: ["Amaretto Sour", "Vervang de helft van de bourbon door amaretto en gebruik iets minder suikersiroop. Zoeter en nootachtig."],
  },
  {
    slug: "moscow-mule",
    name: "Moscow Mule",
    color: ["#f5e3b0", "#c98b4a"],
    short: "Pittig en fris, en in een paar minuten klaar.",
    lead: "Pittig, fris en in een paar minuten klaar. De Moscow Mule is de perfecte cocktail om mee te beginnen.",
    glass: "Koperen mok",
    technique: "Bouwen in het glas",
    level: "Makkelijk",
    time: 3,
    ingredients: [["50 ml", "wodka"], ["15 ml", "vers limoensap"], ["120 ml", "ginger beer"], ["1", "partje limoen"], ["", "takje munt (optioneel)"]],
    tools: "Koperen mok of longdrinkglas, barlepel en ijsblokjes.",
    intro: [
      "De Moscow Mule werd in de jaren veertig populair in de Verenigde Staten, samen met de bekende koperen mok.",
      "Het draait om de ginger beer, niet te verwarren met ginger ale. Ginger beer is pittiger en geeft de cocktail zijn kick.",
    ],
    steps: [
      "Vul de mok of het glas helemaal met ijsblokjes.",
      "Schenk de wodka en het limoensap erin.",
      "Vul aan met koude ginger beer.",
      "Roer één keer kort door met een barlepel, zodat de bubbels blijven.",
      "Garneer met een partje limoen en eventueel een takje munt.",
    ],
    tip: "Zet de koperen mok vooraf in de vriezer. Metaal houdt de kou goed vast, dus je cocktail blijft langer ijskoud.",
    mistakes: [
      "Ginger ale in plaats van ginger beer: te zoet en te weinig pit.",
      "Te hard roeren: dan verdwijnen de bubbels.",
      "Te weinig ijs: een halfvolle mok smelt sneller.",
    ],
    variation: ["Kentucky Mule", "Vervang de wodka door bourbon. Voller en warmer van smaak, lekker in de herfst."],
  },
  {
    slug: "aperol-spritz",
    name: "Aperol Spritz",
    color: ["#ffb35c", "#ea5a24"],
    short: "Bitterzoet, oranje en klaar in twee minuten.",
    lead: "Bitterzoet, oranje en onlosmakelijk verbonden met zomerse terrassen. Zo maak je thuis een Spritz die klopt.",
    glass: "Groot wijnglas",
    technique: "Bouwen in het glas",
    level: "Makkelijk",
    time: 2,
    ingredients: [["90 ml", "prosecco"], ["60 ml", "Aperol"], ["30 ml", "bruiswater"], ["1", "schijfje sinaasappel"]],
    tools: "Groot wijnglas, barlepel en ijsblokjes.",
    intro: [
      "De Spritz komt uit Noord-Italië, waar hij al lang als aperitief wordt gedronken.",
      "Onthoud de verhouding 3-2-1: drie delen prosecco, twee delen Aperol en één deel bruiswater.",
    ],
    steps: [
      "Vul een groot wijnglas met ijsblokjes.",
      "Schenk eerst de prosecco in het glas.",
      "Voeg de Aperol toe.",
      "Maak af met een scheut bruiswater.",
      "Roer één keer voorzichtig en garneer met een schijfje sinaasappel.",
    ],
    tip: "Schenk de prosecco eerst. De Aperol is zwaarder, zakt vanzelf naar beneden en mengt zo zonder dat je hard hoeft te roeren.",
    mistakes: [
      "Te weinig ijs: de Spritz wordt dan snel lauw en waterig.",
      "Prosecco die niet koud is: dan verdwijnen de bubbels meteen.",
      "Te veel roeren: je wilt de prik behouden.",
    ],
    variation: ["Hugo Spritz", "Vervang de Aperol door 20 ml vlierbloesemsiroop en voeg een paar muntblaadjes en een partje limoen toe. Lichter en bloemig."],
  },
];
